### ISSUE TITLE
Error: Unable to get list of AUR packages

### ISSUE THREAD

**Issue by Strykar** [desbma/pacman-hooks#8] opened 2022-02-22 14:30 UTC
@desbma I use aurutils, how do I fix this?
```
$ /usr/bin/check-broken-packages
Error: Unable to get list of AUR packages

Caused by:
    Failed to list packages with pacman
```

**Comment by desbma** [comment] 2022-02-24 17:20
The error is caused by the `pacman -Qqm` command failing.

**Comment by Strykar** [comment] 2022-02-24 20:40
Thanks, just today I converted a Debian package using debtap, and that is the only thing that shows under `pacman -Qqm` and now it does not spit that error. This is still weird since aur packages are installed via
```
[aurpkgs]
SigLevel = Optional TrustAll
Server = file:///home/strykar/arch_packages/aurpkgs
```
via `pacman.conf` and I guess it's unaware of those.

**Comment by desbma** [comment] 2022-02-26 10:42
Maybe `pacman -Qqm` returns an error when no foreign packages are found?
You can confirm via `pacman -Qqm; echo $?`.

**Comment by Strykar** [comment] 2022-02-26 10:44
```
$ pacman -Qqm; echo $?
intezer-protect
0
```

**Comment by desbma** [comment] 2022-02-26 10:45
Can you remove `intezer-protect` and try again?

**Comment by Strykar** [comment] 2022-02-26 10:46
Sure.
```
$ pacman -Qqm; echo $?
1
```
Weirdly, it exits without logging the error above now.

**Comment by desbma** [comment] 2022-02-26 10:54
Thanks, it should be fixed by https://github.com/desbma/pacman-hooks/commit/207665ec92bb379c14f35fff38f4be5e92e6db1c.

**Closed as completed by desbma** 2022-02-26 10:54 UTC

**Comment by Strykar** [comment] 2022-02-26 10:55
Voops, spoke too soon, it does log the error:
```
(4/4) Checking for package with missing dependencies...
Error: Unable to get list of AUR packages

Caused by:
    Failed to list packages with pacman
error: command failed to execute correctly
```

**Comment by desbma** [comment] 2022-02-26 10:57
You need to rebuild `check-broken-packages-pacman-hook-git ` on the latest commit.

**Comment by Strykar** [comment] 2022-02-26 11:04
Yep, done. Thank you for the quick fix!
