### ISSUE TITLE
check-broken-packages-hook reporting missing dependecies for `floorp-bin` aur package but maintainer says that its included

### ISSUE THREAD

**Issue by KAGEYAM4** [desbma/pacman-hooks#15] opened 2023-12-29 20:08 UTC
This is the output of [check-broken-packages-pacman-hook](https://aur.archlinux.org/packages/check-broken-packages-pacman-hook-git/) of https://aur.archlinux.org/packages/floorp-bin ->

```
[phoenix@ArchLinux ~]$ check-broken-packages 
File "/usr/lib/floorp/gmp-clearkey/0.1/libclearkey.so" from package "floorp-bin" is missing dependency "libmozsqlite3.so"
File "/usr/lib/floorp/libmozavcodec.so" from package "floorp-bin" is missing dependency "libmozavutil.so"
File "/usr/lib/floorp/libsoftokn3.so" from package "floorp-bin" is missing dependency "libmozsqlite3.so"
File "/usr/lib/floorp/libxul.so" from package "floorp-bin" is missing dependency "libmozsandbox.so"
File "/usr/lib/floorp/libxul.so" from package "floorp-bin" is missing dependency "liblgpllibs.so"
File "/usr/lib/floorp/libxul.so" from package "floorp-bin" is missing dependency "libmozsqlite3.so"
File "/usr/lib/floorp/libxul.so" from package "floorp-bin" is missing dependency "libmozgtk.so"
File "/usr/lib/floorp/libxul.so" from package "floorp-bin" is missing dependency "libmozwayland.so"
File "/usr/lib/floorp/plugin-container" from package "floorp-bin" is missing dependency "libxul.so"
```

**Comment by desbma** [comment] 2023-12-29 20:31
This packages uses a non standard directory to store its dynamic libraries, and a [script to run a binary](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=floorp-bin#n56) in the same directory as the libraries to ensure they are loaded anyway.
`check-broken-packages` internally uses `ldd` to detect broken dynamic library dependencies, which only searches libraries in standard or explicitly declared directories, so it can not know about this package custom libraries.

See also https://github.com/desbma/pacman-hooks/issues/4#issuecomment-882468437

And for a way to add an exception for a single package: https://github.com/desbma/pacman-hooks/issues/13#issuecomment-1345381941

**Comment by KAGEYAM4** [comment] 2023-12-29 21:12
Thank you, i will  notify the floorp repo about this if they wanna make changes.

**Comment by desbma** [comment] 2023-12-29 21:24
It is unlikely they will, "xxx-bin" packages typically ship dynamic libraries that are not in sync with the Arch ones, and by design don't integrate with the existing Arch libraries and packages.

A proper package that builds from sources should fix this, but note that [`floorp`](https://aur.archlinux.org/packages/floorp) also includes precompiled files (unlike what its name implies), so it should trigger the same issue.

**Comment by xiota** [comment] 2023-12-29 22:36
On my computer, `check-broken-packages` commit f1fa692, produces no warnings about any missing libraries.  The library cache may be out of date.  Update with `ldconfig`.

This is *not* an upstream (floorp) or aur packaging problem.  Numerous packages, whether built from source or repackaged binaries, store files in `/usr/lib/appname` and `/opt/appname`.  The use of both is described on ArchWiki in Electron package guidelines.  `extra/firefox` and other forks share the same structure, which can be examined with `pacman -Fl firefox`.  In case it makes a difference, I will move the install location to `/opt/floorp`.

**Comment by desbma** [comment] 2023-12-29 23:37
> On my computer, check-broken-packages commit f1fa692, produces no warnings about any missing libraries. The library cache may be out of date. Update with ldconfig.

Can you please post the output for example of `ldd /usr/lib/floorp/libxul.so` with `floorp-bin 11.7.1-1`?

**Comment by xiota** [comment] 2023-12-30 02:12
```
$ check-broken-packages

$ ldd /usr/lib/floorp/floorp
        linux-vdso.so.1 (0x00007ffc10b88000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f06d7bd6000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f06d7bd1000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f06d7800000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f06d7ae4000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f06d7abf000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f06d761e000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f06d7cb9000)

$ ldd /usr/lib/floorp/libxul.so | grep 'not found'
        libmozsandbox.so => not found
        liblgpllibs.so => not found
        libmozsqlite3.so => not found
        libmozgtk.so => not found
        libmozwayland.so => not found

$ ldd /usr/lib/firefox/firefox
        linux-vdso.so.1 (0x00007ffe929d5000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f04f7200000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f04f7113000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f04f74b6000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f04f6f31000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f04f75d1000)

$ ldd /usr/lib/firefox/libxul.so | grep 'not found'
        libmozsandbox.so => not found
        libgkcodecs.so => not found
        liblgpllibs.so => not found
        libmozsqlite3.so => not found
        libmozgtk.so => not found
        libmozwayland.so => not found
```

**Comment by KAGEYAM4** [comment] 2023-12-30 06:35
so i am a little bit confused, i ran `sudo ldconfig` but `check-broken-packages` is still reporting the same.

```
[phoenix@ArchLinux ~]$ yay -Qs floorp
local/floorp-bin 11.7.1-1
    Firefox-based web browser focused on performance and customizability
[phoenix@ArchLinux ~]$ yay -Qs check-broken
local/check-broken-packages-pacman-hook-git r89.f1fa692-2
    Pacman hook to check for broken packages
[phoenix@ArchLinux ~]$ sudo ldconfig 
[phoenix@ArchLinux ~]$ check-broken-packages 
File "/usr/lib/floorp/gmp-clearkey/0.1/libclearkey.so" from package "floorp-bin" is missing dependency "libmozsqlite3.so"
File "/usr/lib/floorp/libmozavcodec.so" from package "floorp-bin" is missing dependency "libmozavutil.so"
File "/usr/lib/floorp/libsoftokn3.so" from package "floorp-bin" is missing dependency "libmozsqlite3.so"
File "/usr/lib/floorp/libxul.so" from package "floorp-bin" is missing dependency "libmozsandbox.so"
File "/usr/lib/floorp/libxul.so" from package "floorp-bin" is missing dependency "liblgpllibs.so"
File "/usr/lib/floorp/libxul.so" from package "floorp-bin" is missing dependency "libmozsqlite3.so"
File "/usr/lib/floorp/libxul.so" from package "floorp-bin" is missing dependency "libmozgtk.so"
File "/usr/lib/floorp/libxul.so" from package "floorp-bin" is missing dependency "libmozwayland.so"
File "/usr/lib/floorp/plugin-container" from package "floorp-bin" is missing dependency "libxul.so"
[phoenix@ArchLinux ~]$ 
```

**Comment by xiota** [comment] 2023-12-30 07:00
`aur/floorp-bin` has been updated to install to `/opt/floorp`.  `check-broken-packages` [doesn't check](https://github.com/desbma/pacman-hooks/blob/f1fa692e1dfe0dba3928b144785341c2893a0a37/check-broken-packages/src/main.rs#L234) the `/opt` directory.

Maybe `check-broken-packages` is not working on my computer?

Looks like `check-broken-packages` checks only packages listed by [`pacman -Qqm`](https://github.com/desbma/pacman-hooks/blob/f1fa692e1dfe0dba3928b144785341c2893a0a37/check-broken-packages/src/main.rs#L125-L132).  Any packages in a repository are not checked.  I have chaotic-aur installed, which packages `floorp-bin`, so it is not checked on my computer.

**Comment by KAGEYAM4** [comment] 2023-12-30 08:53
> `aur/floorp-bin` has been updated to install to `/opt/floorp`. `check-broken-packages` [doesn't check](https://github.com/desbma/pacman-hooks/blob/f1fa692e1dfe0dba3928b144785341c2893a0a37/check-broken-packages/src/main.rs#L234) the `/opt` directory.

I looked at the latest commit on pkgbuild script https://aur.archlinux.org/cgit/aur.git/commit/?h=floorp-bin&id=0d6385272419af6b4206b6e8b722acb91eb064b7. 

So if one updates to new floorp-bin, will the old installation be moved to /opt , or will there will be some files left in that case is it best to first remove floorp-bin and then installd it again?

**Comment by xiota** [comment] 2023-12-30 13:37
The package manager will take care of the old files for you.  Unless there is a bug or crash, there should be no old files left behind.

**Comment by desbma** [comment] 2023-12-30 20:28
I have added the ability to run `check-broken-packages` on a single package even if not from AUR in 3eb8084f844bb04dace59f7fe4c4a4cc53b5a5e9, with for example `check-broken-packages firefox`.

As @xiota pointed out, `ldd` reports missing libraries for the `firefox` package even though it is obviously not broken, this should be fixed in ae70a79. `floorp-bin 11.7.1-1` still triggers a warning for `/usr/lib/floorp/gmp-clearkey/0.1/libclearkey.so` but it is the only one now.

**Comment by xiota** [comment] 2023-12-30 21:04
`check-broken-packages` always returns success.  Would be nice if it returned some error code when called to check a package that doesn't exist or if it finds a missing dependency.  Then it could be used in scripts.

**Comment by desbma** [comment] 2023-12-30 21:27
Good point. I have enabled error output in aa77fe3. However I am not sure it is a good idea to return non zero code because a hook that fails aborts the current pacman transaction. So if a user has a broken or weird package, this will make pacman always fail even for unrelated operations.

For scripts you can still check the presence/absence of output, ie with `[ "$(check-broken-packages xxx 2>&1)" ] && echo 'Broken package!'`

**Comment by xiota** [comment] 2023-12-30 22:00
You could add a flag for hook mode, like `check-broken-packages --hook`.  Or put `sh -c 'check-broken-packages || true'` in the hook file.

**Comment by desbma** [comment] 2023-12-30 22:22
@xiota This program is only a hook, so I'm not sure it would make sense to add a `--hook` flag, unless its main goal changes.

@KAGEYAM4 I am closing this since ae70a79 fixes the main issue in `check-broken-packages`, and the package's move to `/opt/` should solve the rest.

**Closed as completed by desbma** 2023-12-30 22:22 UTC
